#cron.yml
---
- name: Copy the cronjob file
  ansible.builtin.copy:
    src: ../files/cronjob
    dest: /etc/cron.d/
    owner: www-data
    group: www-data

- name: "example cronjob"
  ansible.builtin.cron:
    name: "cronjob"
    state: present
    user: www-data
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    job: |
      carton exec script/lufi cron cleanbdd --mode production; carton exec script/lufi cron cleanfiles --mode production; carton exec script/lufi cron watch --mode production    