#dependencies.yml
---
- name: Install Dependencies
  ansible.builtin.apt:
   name:
     - nginx
     - carton
     - build-essential
     - libssl-dev 
     - libio-socket-ssl-perl 
     - liblwp-protocol-https-perl 
     - zlib1g-dev
     - libmojo-sqlite-perl    
   state: present
   
- name: Install Postgress Dev Packages
  apt:
    name:
      - libpq-dev